### ISSUE TITLE
Stuck forever with Loading... due to TypeError

### ISSUE THREAD

**Issue by laukstein** [samdutton/shearch#2]
Error fetching /data/index.json: TypeError: Cannot convert undefined or null to object

![grabilla em3600](https://user-images.githubusercontent.com/183966/53095791-54d84600-3526-11e9-9448-ccf740be66a6.png)

**Comment by samdutton** [comment]
Thanks for this! 

I broke something, which I've now fixed. Could you try hard-reloading?

You may need to clear storage from the Application panel in Chrome DevTools.

**Comment by laukstein** [comment]
@samdutton, so far Ok. But in offline it doesn't work at all.

Try to move offline and refresh page:

![grabilla uh6732](https://user-images.githubusercontent.com/183966/53111773-6e898580-3546-11e9-8e55-27566809fd54.png)

**Comment by samdutton** [comment]
Thanks so much for this!

I discovered that the app wasn't caching index.html for URLs with a hash value (such as shearch.me#bug).

I've fixed this in [this commit](https://github.com/samdutton/shearch/commit/a178c5ef2003151799edc3e6aeac00f1322742fc).

You'll need to do a hard reload to try again.

Let me know if you're still experiencing problems.

**Comment by laukstein** [comment]
@samdutton, offline still doesn't work as expected. the resources are cached only after second page visit.
Lets say I open https://shearch.me/#ham.3 - ServiceWorker is registered and noting cached for offline. When after goes offline and page is refreshed, shows:

![grabilla em2256](https://user-images.githubusercontent.com/183966/53175893-9b48a600-35f5-11e9-8c44-458e10ffc462.png)

While online when page is visited for 2nd time, then all resources gets cached, and on offline results:

![grabilla g14356](https://user-images.githubusercontent.com/183966/53175940-b87d7480-35f5-11e9-97ec-ccdae861c2fe.png)

**Comment by samdutton** [comment]
Not ignoring this — just trying to work out what's best :).

AIUI the behaviour you describe is 'working as intended' for service workers. 

However, I agree that that isn't *really* what users will probably expect. I think I'm going to cache all the app files on first load. 

I might even opt for asking the user if they want to download all the texts — not sure what's best.

(See also #3.)

**Comment by laukstein** [comment]
@samdutton, do you test before committing? Now ServiceWorker (offline compatibility) doesn't work at all:

![grabilla q11344](https://user-images.githubusercontent.com/183966/53289548-046c1d00-37a0-11e9-88d9-e28c316fe723.png)

**Comment by samdutton** [comment]
> @samdutton, do you test before committing? Now ServiceWorker (offline compatibility) doesn't work at all

Yes, I do test before committing :).

What I didn't test, unfortunately, was #3 — which I didn't realise deletes sw.js (since it assumes a build step).

shearch.me is working again. Apologies for the interruption in service!

**Comment by laukstein** [comment]
👍 seems working. I think we can close this task.

**Comment by samdutton** [comment]
👍

Thanks again — and I'll sort out the (pre)caching.
